version: 2.1
orbs:
  codecov: codecov/codecov@4.0.1
  node: circleci/node@5.1.0
  win: circleci/windows@5.0

commands:
  setup_google_dns:
    steps:
      - run:
          name: "Configure Google DNS"
          command: |
            sudo cp /etc/resolv.conf /etc/resolv.conf.backup
            echo "nameserver 127.0.0.11" | sudo tee /etc/resolv.conf
            echo "nameserver 8.8.8.8" | sudo tee -a /etc/resolv.conf
            echo "nameserver 8.8.4.4" | sudo tee -a /etc/resolv.conf
  setup_litellm_enterprise_pip:
    steps:
      - run:
          name: "Install local version of litellm-enterprise"
          command: |
            cd enterprise
            python -m pip install -e .
            cd ..

jobs:
  using_litellm_on_windows:
    executor:
      name: win/default
      shell: powershell.exe
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install Python
          command: |
            choco install python --version=3.11.0 -y
            refreshenv
            python --version
      - run:
          name: Install Dependencies
          command: |
            python -m pip install --upgrade pip
            pip install pytest
            pip install .
      - run:
          name: Run Windows-specific test
          command: |
            python -m pytest tests/windows_tests/test_litellm_on_windows.py -v
  mypy_linting:
    docker:
      - image: cimg/python:3.12
        auth:
          username: ${DOCKERHUB_USERNAME}
          password: ${DOCKERHUB_PASSWORD}
    working_directory: ~/project
    resource_class: medium
    steps:
      - checkout
      - setup_google_dns
      - run:
          name: Install Dependencies
          command: |
            python -m pip install --upgrade pip
            python -m pip install -r requirements.txt
            pip uninstall fastuuid -y
            pip install "mypy==1.18.2"
      - run:
          name: MyPy Type Checking
          command: |
            cd litellm
            python -m mypy .
            cd ..
          no_output_timeout: 10m
  local_testing:
    docker:
      - image: steadson/litellm-ci:v1.0
        auth:
          username: ${steadson}
          password: ${Asiye0802!}
    working_directory: ~/project
    steps:
      - checkout
      - setup_google_dns
      - run:
          name: Show git commit hash
          command: |
            echo "Git commit hash: $CIRCLE_SHA1"
      - setup_litellm_enterprise_pip
      - run:
          name: Run prisma ./docker/entrypoint.sh
          command: |
            set +e
            chmod +x docker/entrypoint.sh
            ./docker/entrypoint.sh
            set -e
      - run:
          name: Black Formatting
          command: |
            cd litellm
            python -m pip install black
            python -m black .
            cd ..
      - run:
          name: Run tests
          command: |
            pwd
            ls
            python -m pytest -vv tests/local_testing --cov=litellm --cov-report=xml --junitxml=test-results/junit.xml --durations=5 -k "not test_python_38.py and not test_basic_python_version.py and not router and not assistants and not langfuse and not caching and not cache" -n 4
          no_output_timeout: 120m
      - run:
          name: Rename the coverage files
          command: |
            mv coverage.xml local_testing_coverage.xml
            mv .coverage local_testing_coverage
      - store_test_results:
          path: test-results
      - persist_to_workspace:
          root: .
          paths:
            - local_testing_coverage.xml
            - local_testing_coverage
workflows:
  version: 2
  build_and_test:
    jobs:
      - using_litellm_on_windows:
          filters:
            branches:
              only:
                - main
                - /litellm_.*/
      - mypy_linting:
          filters:
            branches:
              only:
                - main
                - /litellm_.*/
      - local_testing:
          filters:
            branches:
              only:
                - main
                - /litellm_.*/